// Code generated by "stringer -type Fat"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Expression-1]
	_ = x[Parametric-2]
	_ = x[Polymorph-4]
	_ = x[Constrain-8]
	_ = x[Argument-16]
	_ = x[Pattern-32]
	_ = x[Partial-64]
	_ = x[Reverse-128]
	_ = x[Lambda-256]
	_ = x[Fixity-512]
	_ = x[Result-1024]
	_ = x[Assign-2048]
	_ = x[Scope-4096]
	_ = x[Apply-8192]
	_ = x[Curry-16384]
	_ = x[Bind-32768]
	_ = x[Call-65536]
	_ = x[Map-131072]
	_ = x[Dot-262144]
	_ = x[Nop-0]
}

const _Fat_name = "NopExpressionParametricPolymorphConstrainArgumentPatternPartialReverseLambdaFixityResultAssignScopeApplyCurryBindCallMapDot"

var _Fat_map = map[Fat]string{
	0:      _Fat_name[0:3],
	1:      _Fat_name[3:13],
	2:      _Fat_name[13:23],
	4:      _Fat_name[23:32],
	8:      _Fat_name[32:41],
	16:     _Fat_name[41:49],
	32:     _Fat_name[49:56],
	64:     _Fat_name[56:63],
	128:    _Fat_name[63:70],
	256:    _Fat_name[70:76],
	512:    _Fat_name[76:82],
	1024:   _Fat_name[82:88],
	2048:   _Fat_name[88:94],
	4096:   _Fat_name[94:99],
	8192:   _Fat_name[99:104],
	16384:  _Fat_name[104:109],
	32768:  _Fat_name[109:113],
	65536:  _Fat_name[113:117],
	131072: _Fat_name[117:120],
	262144: _Fat_name[120:123],
}

func (i Fat) String() string {
	if str, ok := _Fat_map[i]; ok {
		return str
	}
	return "Fat(" + strconv.FormatInt(int64(i), 10) + ")"
}
