// Code generated by "stringer -type Fat"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Expression-1]
	_ = x[Parametric-2]
	_ = x[Parameter-4]
	_ = x[Polymorph-8]
	_ = x[Constrain-16]
	_ = x[Operator-32]
	_ = x[Argument-64]
	_ = x[Nullary-128]
	_ = x[Pattern-256]
	_ = x[Partial-512]
	_ = x[Reverse-1024]
	_ = x[Lambda-2048]
	_ = x[Fixity-4096]
	_ = x[Result-8192]
	_ = x[Assign-16384]
	_ = x[Scope-32768]
	_ = x[Apply-65536]
	_ = x[Unary-131072]
	_ = x[Nary-262144]
	_ = x[Eval-524288]
	_ = x[Map-1048576]
	_ = x[Dot-2097152]
	_ = x[Nop-0]
}

const _Fat_name = "NopExpressionParametricParameterPolymorphConstrainOperatorArgumentNullaryPatternPartialReverseLambdaFixityResultAssignScopeApplyUnaryNaryEvalMapDot"

var _Fat_map = map[Fat]string{
	0:       _Fat_name[0:3],
	1:       _Fat_name[3:13],
	2:       _Fat_name[13:23],
	4:       _Fat_name[23:32],
	8:       _Fat_name[32:41],
	16:      _Fat_name[41:50],
	32:      _Fat_name[50:58],
	64:      _Fat_name[58:66],
	128:     _Fat_name[66:73],
	256:     _Fat_name[73:80],
	512:     _Fat_name[80:87],
	1024:    _Fat_name[87:94],
	2048:    _Fat_name[94:100],
	4096:    _Fat_name[100:106],
	8192:    _Fat_name[106:112],
	16384:   _Fat_name[112:118],
	32768:   _Fat_name[118:123],
	65536:   _Fat_name[123:128],
	131072:  _Fat_name[128:133],
	262144:  _Fat_name[133:137],
	524288:  _Fat_name[137:141],
	1048576: _Fat_name[141:144],
	2097152: _Fat_name[144:147],
}

func (i Fat) String() string {
	if str, ok := _Fat_map[i]; ok {
		return str
	}
	return "Fat(" + strconv.FormatInt(int64(i), 10) + ")"
}
