// Code generated by "stringer -type Fix"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Suffix-1]
	_ = x[Infix-2]
	_ = x[Postfix-4]
	_ = x[Nullary-0]
}

const (
	_Fix_name_0 = "NullarySuffixInfix"
	_Fix_name_1 = "Postfix"
)

var (
	_Fix_index_0 = [...]uint8{0, 7, 13, 18}
)

func (i Fix) String() string {
	switch {
	case i <= 2:
		return _Fix_name_0[_Fix_index_0[i]:_Fix_index_0[i+1]]
	case i == 4:
		return _Fix_name_1
	default:
		return "Fix(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
