// Code generated by "stringer -type Lgc"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[And-0]
	_ = x[Or-1]
	_ = x[Xor-2]
	_ = x[Nor-3]
	_ = x[Neg - -1]
}

const _Lgc_name = "NegAndOrXorNor"

var _Lgc_index = [...]uint8{0, 3, 6, 8, 11, 14}

func (i Lgc) String() string {
	i -= -1
	if i < 0 || i >= Lgc(len(_Lgc_index)-1) {
		return "Lgc(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Lgc_name[_Lgc_index[i]:_Lgc_index[i+1]]
}
