// Code generated by "stringer -type Logic"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Xor-1]
	_ = x[Or-2]
	_ = x[Pip-4]
	_ = x[And-0]
	_ = x[Negation-255]
}

const (
	_Logic_name_0 = "AndXorOr"
	_Logic_name_1 = "Pip"
	_Logic_name_2 = "Negation"
)

var (
	_Logic_index_0 = [...]uint8{0, 3, 6, 8}
)

func (i Logic) String() string {
	switch {
	case i <= 2:
		return _Logic_name_0[_Logic_index_0[i]:_Logic_index_0[i+1]]
	case i == 4:
		return _Logic_name_1
	case i == 255:
		return _Logic_name_2
	default:
		return "Logic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
