// Code generated by "stringer -type Ord"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MuchLesser - -2]
	_ = x[Lesser - -1]
	_ = x[Equal-0]
	_ = x[Greater-1]
	_ = x[MuchGreater-2]
}

const _Ord_name = "MuchLesserLesserEqualGreaterMuchGreater"

var _Ord_index = [...]uint8{0, 10, 16, 21, 28, 39}

func (i Ord) String() string {
	i -= -2
	if i < 0 || i >= Ord(len(_Ord_index)-1) {
		return "Ord(" + strconv.FormatInt(int64(i+-2), 10) + ")"
	}
	return _Ord_name[_Ord_index[i]:_Ord_index[i+1]]
}
