// Code generated by "stringer -type OrdId"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Lesser - -1]
	_ = x[Equal-0]
	_ = x[Greater-1]
}

const _OrdId_name = "LesserEqualGreater"

var _OrdId_index = [...]uint8{0, 6, 11, 18}

func (i OrdId) String() string {
	i -= -1
	if i < 0 || i >= OrdId(len(_OrdId_index)-1) {
		return "OrdId(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _OrdId_name[_OrdId_index[i]:_OrdId_index[i+1]]
}
