// Code generated by "stringer -type Rln"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[All-1]
	_ = x[Any-2]
	_ = x[Once-3]
	_ = x[Exists-4]
	_ = x[ExistsNot-5]
	_ = x[Superset-6]
	_ = x[NoSuperset-7]
	_ = x[Subset-8]
	_ = x[NoSubset-9]
	_ = x[Union-10]
	_ = x[Intersection-11]
	_ = x[Succeessor-12]
	_ = x[Predecessor-13]
	_ = x[Unrelated-0]
}

const _Rln_name = "UnrelatedAllAnyOnceExistsExistsNotSupersetNoSupersetSubsetNoSubsetUnionIntersectionSucceessorPredecessor"

var _Rln_index = [...]uint8{0, 9, 12, 15, 19, 25, 34, 42, 52, 58, 66, 71, 83, 93, 104}

func (i Rln) String() string {
	if i < 0 || i >= Rln(len(_Rln_index)-1) {
		return "Rln(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rln_name[_Rln_index[i]:_Rln_index[i+1]]
}
