// Code generated by "stringer -type Trp"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[False - -1]
	_ = x[Undefined-0]
	_ = x[True-1]
}

const _Trp_name = "FalseUndefinedTrue"

var _Trp_index = [...]uint8{0, 5, 14, 18}

func (i Trp) String() string {
	i -= -1
	if i < 0 || i >= Trp(len(_Trp_index)-1) {
		return "Trp(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Trp_name[_Trp_index[i]:_Trp_index[i+1]]
}
