// Code generated by "stringer -type Truth"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[False - -1]
	_ = x[Undefined-0]
	_ = x[True-1]
}

const _Truth_name = "FalseUndefinedTrue"

var _Truth_index = [...]uint8{0, 5, 14, 18}

func (i Truth) String() string {
	i -= -1
	if i < 0 || i >= Truth(len(_Truth_index)-1) {
		return "Truth(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Truth_name[_Truth_index[i]:_Truth_index[i+1]]
}
