// Code generated by "stringer -type TruthId"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[False-0]
	_ = x[True-1]
	_ = x[Uniq-2]
	_ = x[Any-3]
	_ = x[All-4]
	_ = x[Not-5]
	_ = x[And-6]
	_ = x[Xor-7]
	_ = x[Or-8]
	_ = x[LT-9]
	_ = x[GT-10]
}

const _TruthId_name = "FalseTrueUniqAnyAllNotAndXorOrLTGT"

var _TruthId_index = [...]uint8{0, 5, 9, 13, 16, 19, 22, 25, 28, 30, 32, 34}

func (i TruthId) String() string {
	if i < 0 || i >= TruthId(len(_TruthId_index)-1) {
		return "TruthId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TruthId_name[_TruthId_index[i]:_TruthId_index[i+1]]
}
